- name: Install mysql
  yum: name={{ item }} disable_gpg_check=yes enablerepo=remi
  with_items:
    - mysql
    - mysql-devel
    - mysql-server
    - MySQL-python
    - libselinux-python
    - libsemanage-python

- name: Start the MySQL service
  sudo: yes
  service:
    name: mysqld
    state: started
    enabled: true

- name: update mysql root password for all root accounts
  sudo: yes
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "root"
    login_user: root
    login_password: "root"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
