- name: Create Folder for Session
  file: path=/var/lib/php/session state=directory owner=nginx group=nobody mode=770

- name: Copy www.conf file
  template: src=www.conf dest=/etc/php-fpm.d/www.conf

- name: Copy error.log file
  copy: src=error.log dest=/var/log/php-fpm/error.log owner=nginx group=nginx mode=770

- name: Copy slow.log file
  copy: src=slow.log dest=/var/log/php-fpm/slow.log owner=nginx group=nginx mode=770

- name: Add php-fpm to chkconfig
  command: chkconfig --add php-fpm

- name: Auto start php-fpm
  command: chkconfig --levels 235 php-fpm on
  notify: restart php-fpm

- name: Create session directory
  shell: mkdir -p /tmp/session
  notify: restart php-fpm

- name: Give the correct ownership and permission to session directory
  shell: chown -R vagrant:vagrant /tmp/session && chmod -R 0777 /tmp/session
  notify: restart php-fpm
